"""agregar columna deadline

Revision ID: 154980f24cfe
Revises: 94e5a96d2ed9
Create Date: 2026-01-27 19:54:13.879114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154980f24cfe'
down_revision: Union[str, Sequence[str], None] = '94e5a96d2ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
